[package]
name = "tx-orderer-primitives"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha3 = { workspace = true }
const-hex = { workspace = true }
ethers-core = { workspace = true }
tracing = { workspace = true }
serde_with = { workspace = true }
tokio = { workspace = true }
dashmap = { workspace = true }
clap = { workspace = true }
toml = { workspace = true }
reqwest = { workspace = true }
radius-sdk = { workspace = true }