[workspace]
members = [
    "src",
    "primitives",
    "shared", 
    "node",
    "cli"
]
resolver = "2"

[workspace.dependencies]
tx-orderer-primitives = { path = "primitives" }
tx-orderer-shared = { path = "shared" }
tx-orderer-node = { path = "node" }
tx-orderer-cli = { path = "cli" }

# External
chrono = "0.4.38"
clap = { version = "4.4.7", features = ["derive"] }
const-hex = "1.12"
ethers-core = "2.0"
local-ip-address = "0.6"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.127"
sha3 = "0.10"
tokio-tungstenite = "0.23"
tokio = { version = "1.37.0", features = ["full"] }
toml = "0.8.13"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
reqwest = { version = "0.12.4", features = ["json"] }
dashmap = "5.4"
serde_with = "3"
pyroscope = "0.5.4"
pyroscope_pprofrs = "0.2"
futures = "0.3"
tokio-stream = "0.1"

# Radius Extern 
skde = { git = "https://github.com/radiusxyz/skde", rev = "69e70ac0ab071000b3d13557cdbed43ffeddc878" }
radius-sdk = { git = "https://github.com/radiusxyz/radius-sdk-rs", rev = "7fbbffeb6ab7807a489bb5a7bc03eaa66031f398", features = ["full"] }

[patch.crates-io]
risc0-zkvm = { git = "https://github.com/risc0/risc0", tag = "v2.0.1", package = "risc0-zkvm" }